hooks:
  - &base
    language: python
    types: [python]
    require_serial: true
  - &mypy
    id: mypy
    name: mypy
    entry: mypy
    <<: *base
  - &flake8
    id: flake8
    name: flake8
    entry: flake8
    <<: *base
  - &isort
    id: isort
    name: isort
    entry: isort
    <<: *base

repos:
  - repo: local
    hooks:
      - <<: *mypy
        files: ^install/
      - <<: *mypy
        name: mypy (py2)
        files: ^install/
        args: ['--py2']
      - <<: *flake8
        files: ^install/
      - <<: *isort
        files: ^install/
        args: ['--check-only', '--diff']

